In [1]:
import numpy as np

In [2]:
a = np.array([5,6,9])
a[0]

5

In [3]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim # Print dimensions

2

In [4]:
a = np.array([5,6,9])
a.ndim

1

In [5]:
a = np.array([[1,2], [3,4], [5,6]])
a.itemsize # size of each element => a number is 8 byte in np

8

In [6]:
a.dtype

dtype('int64')

In [8]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.int32)
a.itemsize

4

In [9]:
a.size # Number of elements in total

6

In [10]:
a.shape # List dimensions -> rows, cols, ...

(3, 2)

In [11]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.complex_)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

### Placeholder

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.arange(5) # Same as range in python

array([0, 1, 2, 3, 4])

In [15]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [16]:
np.arange(1, 5, 2) # with steps

array([1, 3])

In [17]:
np.linspace(1, 5, 10) # Generate 10 numbers from 1 to 5 inclusively that are linearly spaced out

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

### Reshape

In [19]:
a = np.array([[1,2], [3,4], [5,6]])
a.shape

(3, 2)

In [20]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**NOTE:** The dimensions need to be compatible with number of elements (i.e array.size)

### Ravel (Flatten)

In [24]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

### Mathematical Ops

In [25]:
a.min()

1

In [26]:
a.max()

6

In [27]:
a.sum()

21

![Axis](images/axis.png)

In [28]:
a.sum(axis=0)

array([ 9, 12])

In [29]:
a.sum(axis=1)

array([ 3,  7, 11])

In [30]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [31]:
np.std(a) # standard deviation

1.707825127659933

In [36]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a)
print()

print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [37]:
a+b

array([[ 6,  8],
       [10, 12]])

### Dot Product

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

There are multiple cases for input a and b.

In [38]:
# In this case, since both a and b are 2D arrays, np.dot does a matrix multiplication between the two matrices.

a.dot(b) # Dot product

array([[19, 22],
       [43, 50]])