### Topics

- Indexing and slicing

- Iterating through arrays

- Stacking together two arrays

- Indexing with boolean arrays

In [1]:
import numpy as np

In [2]:
n = [6,7,8]
n[0:1]

[6]

In [3]:
n[-1]

8

In [4]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [5]:
a[-1]

8

In [6]:
a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [7]:
a[1,2] # Index in a multi-dimensional (Row 1, Column 2, 0-based index)

3

In [8]:
a[0:2,2] # Row 0 and 1 + Take Column 2

array([8, 3])

In [9]:
a[-1] # Last row

array([9, 3, 2])

In [10]:
a[-1, 0:2] # Last row + Get Column 0 and 1

array([9, 3])

In [12]:
a[:, 1:3] # All Rows + Get Column 1 and 2

array([[7, 8],
       [2, 3],
       [3, 2]])

In [13]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [15]:
print(a.flat)

for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [21]:
test = [1,2,3]
i = iter(test)

# Note: for in loop will use next() if it's iterator. So if we call next() later on, it will throw StopIteration.
for el in i:
    print(el)

print()

# print(next(i))
# print(next(i))
# print(next(i))

1
2
3



### Stacking

In [23]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
# Vertical Stack

np.vstack((a, b)) # Receives in a tuple for the order of vertical stacking

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
# Horizontal Stack

np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [36]:
print(np.stack([a, b], axis=0).shape)
print(np.stack([a, b], axis=1).shape)

# axis is the index of the new axis in the result dimensions
"""
>>> arrays = [np.random.randn(3, 4) for _ in range(10)]
>>> np.stack(arrays, axis=0).shape
(10, 3, 4)
>>> np.stack(arrays, axis=1).shape
(3, 10, 4)
>>> np.stack(arrays, axis=2).shape
(3, 4, 10)

Each element shape is (3,4)
The new axis is 10 since we are trying to stack these 10 elements in some manner

axis=0: axis 10 is at index 0 of result dimension
axis=2: axis 10 is at index 2 of result dimension
"""

(2, 3, 2)
(3, 2, 2)


In [37]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
np.hsplit(a, 3) # (2,15) -> 3 arrays of shape (2,5) -> which is 2nd dimension 15 divided by 3

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [39]:
np.vsplit(a, 2) # (2,15) -> 2 arrays of shape (1,15) -> which is 1st dimension 2 divided by 2

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

### Indexing with Boolean Arrays

In [41]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
a[b] # Mask

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
type(a[b])

numpy.ndarray

In [46]:
# Update value in ndarray based on mask
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])