In [59]:
import numpy as np

In [60]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [62]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [63]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [64]:
"""
C Is Contiguous layout. Mathematically speaking, row major.
F Is Fortran contiguous layout. Mathematically speaking, column major.
A Is any order. Generally don't use this.
K Is keep order. Generally don't use this.
"""

for x in np.nditer(a, order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [77]:
for x in np.nditer(a, order='F'):
    print(x)

print()

for x in np.nditer(a): # order = K by default
    print(x)

0
16
64
1
25
81
4
36
100
9
49
121

0
1
4
9
16
25
36
49
64
81
100
121


In [66]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [67]:
"""
The Ellipsis object in Python is a built-in constant that serves as a placeholder or a marker in Python code.
In numpy, this object can be used in slicing (square bracket) with special meaning.
https://stackoverflow.com/questions/118370/how-do-you-use-the-ellipsis-slicing-syntax-in-python
"""

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [69]:
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

In [73]:
# Search General Broadcasting Rules of NumPy

for x,y in np.nditer([a, b]): # To do this, the arrays must have same dimensions (then maybe end with 1)
    print(x, y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
